version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
    stdin_open: true
    tty: true

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 55432:5432
